name: Contribution Request

description: Request access to contribute to the Excalidraw plugin documentation on the wiki

title: '[Contribution] Request to Contribute to Wiki'

labels: [collaboration-request]

assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Contribution Request

        Thank you for your interest in contributing to the Excalidraw Plugin wiki! To help me understand how you’d like to contribute, please provide the following details:

        1. **Contribution Area**: Describe what areas of the wiki you’re interested in contributing to (e.g., fixing typos, adding new tutorials, improving existing content).
        2. **Experience**: Briefly describe your experience with Excalidraw or Obsidian and any relevant background that will help with the contribution.
        3. **Additional Information**: Any other information or questions you may have.

        **Example:**
        ```
        - Contribution Area: Adding a tutorial on advanced Excalidraw features
        - Experience: Regular user of Excalidraw and experienced in creating tutorials
        - Additional Information: Looking forward to contributing!
        ```

        Once I review your request, I will get back to you with instructions on how to proceed. Thank you for helping improve our documentation!

        ---
        Zsolt

  - type: textarea
    attributes:
      label: Contribution Details
      description: Provide details about your contribution request.
      placeholder: |
        - Contribution Area: Adding a tutorial on advanced Excalidraw features
        - Experience: Regular user of Excalidraw and experienced in creating tutorials
        - Additional Information: Looking forward to contributing!

  - type: checkboxes
    id: verify_guidelines
    attributes:
      label: Read the [WIKI Contributors Guidelines](https://github.com/zsviczian/obsidian-excalidraw-plugin/wiki/Contributor-Guidelines) before submitting the request.
      options:
        - label: Yes, I have read and understood the [Contributors Guidelines](https://github.com/zsviczian/obsidian-excalidraw-plugin/wiki/Contributor-Guidelines)

