// This file was generated by lezer-generator. You probably shouldn't edit it.
/*
Obsidian uses a slightly modified version of the hypermd parser for math blocks
found at https://github.com/laobubu/HyperMD/blob/071ce236605bb7693efa6d4b829c39413a3d37fb/src/mode/hypermd.ts#L329-L336 
where spaces are replaced with `_` and the mathlevel of 1|2 is replaced with `math-block` for display math and nothing for inline math
create from the following grammar (where we remove the upper-cases):
@top Document { Formatting_formatting-math_formatting-math-begin_keyword_math_math-block Math Formatting_formatting-math_formatting-math-end_keyword_math_math- }

Formatting_formatting-math_formatting-math-begin_keyword_math_math-block { "" }
Math { any* }
Formatting_formatting-math_formatting-math-end_keyword_math_math- { "" }

@tokens {
    any { _ }
}
*/
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "zOOOO?MrOOQOPOOOOOO'#Ca'#CaOYOPO'#C_OOOO?MtOOOOO-E6_-E6_QOOOOO",
  stateData: "b~OVQOURP~OVQOURX~O",
  goto: "fUPPVY]`RPORSPRUSQRPRTR",
  nodeNames: "⚠ Document formatting_formatting-math_formatting-math-begin_keyword_math_math-block math formatting_formatting-math_formatting-math-end_keyword_math_math-",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "i~RRO;'S[;'S;=`a;=`O[~aOV~~fPV~;=`<%l[",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
