// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "[OQOPOOQOOOOO",
  stateData: "V~ORPO~O",
  goto: "QPP",
  nodeNames: "⚠ math",
  maxTerm: 3,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "{~RRO;'S[;'S;=`j;=`O[~aRR~O;'S[;'S;=`j;=`O[~oSR~O;'S[;'S;=`j;=`<%l[<%lO[",
  tokenizers: [0],
  topRules: {"math":[0,1]},
  tokenPrec: 0
})
