// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "zOOOO?MrOOQOPOOOOOO'#Ca'#CaOYOPO'#C_OOOO?MtOOOOO-E6_-E6_QOOOOO",
  stateData: "b~OVQOURP~OVQOURX~O",
  goto: "fUPPVY]`RPORSPRUSQRPRTR",
  nodeNames: "⚠ Document math-begin math math-end",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "i~RRO;'S[;'S;=`a;=`O[~aOV~~fPV~;=`<%l[",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
