import {
  defaultKeymap,
  history,
  historyKeymap,
  indentWithTab,
} from "@codemirror/commands";
import { css } from "@codemirror/lang-css";
import {
  bracketMatching,
  HighlightStyle,
  indentOnInput,
  syntaxHighlighting,
} from "@codemirror/language";
import { EditorState } from "@codemirror/state";
import {
  drawSelection,
  EditorView,
  highlightActiveLine,
  highlightActiveLineGutter,
  keymap,
  lineNumbers,
} from "@codemirror/view";
import { tags } from "@lezer/highlight";

const obsidianCSSHighlightStyle = HighlightStyle.define([
  {
    tag: tags.comment,
    color: "var(--code-comment, var(--text-muted))",
  },
  {
    tag: [tags.className, tags.tagName, tags.labelName, tags.namespace],
    color: "var(--code-tag, var(--color-yellow))",
  },
  {
    tag: [tags.propertyName, tags.attributeName],
    color: "var(--code-property, var(--color-orange))",
  },
  {
    tag: [tags.keyword, tags.definitionKeyword, tags.operatorKeyword],
    color: "var(--code-keyword, var(--color-pink))",
  },
  {
    tag: tags.modifier,
    color: "var(--code-important, var(--color-pink))",
  },
  {
    tag: [tags.string, tags.attributeValue],
    color: "var(--code-string, var(--color-green))",
  },
  {
    tag: [tags.atom, tags.number, tags.bool, tags.unit, tags.color],
    color: "var(--code-value, var(--color-cyan))",
  },
  {
    tag: tags.variableName,
    color: "var(--code-function, var(--color-blue))",
  },
  {
    tag: tags.operator,
    color: "var(--code-operator, var(--text-normal))",
  },
  {
    tag: tags.punctuation,
    color: "var(--code-punctuation, var(--text-muted))",
  },
  {
    tag: tags.name,
    color: "var(--code-normal, var(--text-normal))",
  },
]);

const MARKDOWN_IMAGE_CSS_TEMPLATE_MARKER =
  "/* Excalidraw Markdown image CSS boilerplate */";
const TRANSCLUSION_CSS_TEMPLATE_MARKER =
  "/* Excalidraw transclusion CSS boilerplate */";

/** A commented starting point for styling a complete Markdown image. */
export const MARKDOWN_IMAGE_CSS_BOILERPLATE = `${MARKDOWN_IMAGE_CSS_TEMPLATE_MARKER}
/* Uncomment and adjust only the declarations you need. */

/* Document */
.excalidraw-md-host {
  /* padding: 12px 18px; */
  /* font-size: 16px; */
  /* line-height: 1.5; */
  /* background-color: transparent; */
}

/* Headings */
.excalidraw-md-host h1,
.excalidraw-md-host h2,
.excalidraw-md-host h3,
.excalidraw-md-host h4,
.excalidraw-md-host h5,
.excalidraw-md-host h6 {
  /* color: currentColor; */
  /* font-family: inherit; */
  /* line-height: 1.2; */
  /* margin-block: 1em 0.5em; */
}

/* Paragraphs and lists */
.excalidraw-md-host p,
.excalidraw-md-host ul,
.excalidraw-md-host ol {
  /* margin-block: 0.75em; */
}

/* Links */
.excalidraw-md-host a,
.excalidraw-md-host .internal-link {
  /* color: #086ddd; */
  /* text-decoration: underline; */
}

/* Blockquotes */
.excalidraw-md-host blockquote {
  /* margin-inline: 0; */
  /* padding: 10px 16px; */
  /* border-left: 4px solid currentColor; */
  /* background-color: rgba(127, 127, 127, 0.1); */
}

/* Inline and fenced code */
.excalidraw-md-host :not(pre) > code,
.excalidraw-md-host pre {
  /* font-family: Consolas, "Courier New", monospace; */
  /* font-size: 0.9em; */
  /* border-radius: 4px; */
}

/* Tables */
.excalidraw-md-host table {
  /* width: 100%; */
  /* border-collapse: collapse; */
}
.excalidraw-md-host th,
.excalidraw-md-host td {
  /* padding: 6px 8px; */
  /* border: 1px solid currentColor; */
}

/* Images */
.excalidraw-md-host img {
  /* display: block; */
  /* max-width: 100%; */
  /* margin-block: 12px; */
  /* border-radius: 4px; */
}

/* Callouts */
.excalidraw-md-host .callout {
  /* padding: 12px; */
  /* border-radius: 6px; */
  /* background-color: rgba(127, 127, 127, 0.1); */
}

/* Outer border generated by the Border setting */
.excalidraw-md-border {
  /* stroke-width: 2px; */
  /* stroke-dasharray: none; */
}`;

/** A commented starting point for styling Markdown rendered inside transclusions. */
export const TRANSCLUSION_CSS_BOILERPLATE = `${TRANSCLUSION_CSS_TEMPLATE_MARKER}
/* These rules run inside each transcluded Markdown SVG. */
/* Uncomment and adjust only the declarations you need. */

/* Transcluded document */
.excalidraw-md-host {
  /* padding: 10px 14px; */
  /* font-size: 15px; */
  /* line-height: 1.45; */
  /* background-color: transparent; */
}

/* Headings */
.excalidraw-md-host h1,
.excalidraw-md-host h2,
.excalidraw-md-host h3,
.excalidraw-md-host h4,
.excalidraw-md-host h5,
.excalidraw-md-host h6 {
  /* color: currentColor; */
  /* font-family: inherit; */
  /* line-height: 1.2; */
}

/* Paragraphs and lists */
.excalidraw-md-host p,
.excalidraw-md-host ul,
.excalidraw-md-host ol {
  /* margin-block: 0.6em; */
}

/* Links */
.excalidraw-md-host a,
.excalidraw-md-host .internal-link {
  /* color: #086ddd; */
  /* text-decoration: underline; */
}

/* Blockquotes and callouts */
.excalidraw-md-host blockquote,
.excalidraw-md-host .callout {
  /* padding: 10px 14px; */
  /* border-radius: 4px; */
  /* background-color: rgba(127, 127, 127, 0.1); */
}

/* Code */
.excalidraw-md-host :not(pre) > code,
.excalidraw-md-host pre {
  /* font-size: 0.9em; */
  /* border-radius: 4px; */
}

/* Images and tables */
.excalidraw-md-host img {
  /* max-width: 100%; */
  /* border-radius: 4px; */
}
.excalidraw-md-host table {
  /* width: 100%; */
  /* border-collapse: collapse; */
}

/* Border generated by the Transclusion border setting */
.excalidraw-md-border {
  /* stroke-width: 2px; */
  /* stroke-dasharray: none; */
}`;

/**
 * Small CodeMirror 6 wrapper for the sidepanel's CSS fields.
 *
 * The wrapper owns its editor lifecycle so clearing or rebuilding the sidepanel
 * cannot leave CodeMirror observers attached to detached DOM nodes.
 */
export class CSSCodeEditor {
  private readonly editor: EditorView;

  constructor(
    parent: HTMLElement,
    value: string,
    ariaLabel: string,
    onChange: (value: string) => void,
  ) {
    this.editor = new EditorView({
      state: EditorState.create({
        doc: value,
        extensions: [
          lineNumbers(),
          highlightActiveLineGutter(),
          history(),
          drawSelection(),
          indentOnInput(),
          bracketMatching(),
          syntaxHighlighting(obsidianCSSHighlightStyle),
          css(),
          EditorView.lineWrapping,
          highlightActiveLine(),
          keymap.of([indentWithTab, ...defaultKeymap, ...historyKeymap]),
          EditorView.contentAttributes.of({
            "aria-label": ariaLabel,
            autocapitalize: "off",
            autocomplete: "off",
            spellcheck: "false",
          }),
          EditorView.updateListener.of((update) => {
            if (update.docChanged) {
              onChange(update.state.doc.toString());
            }
          }),
        ],
      }),
      parent,
    });
  }

  /** Appends a template once, preserving any CSS already entered by the user. */
  public insertBoilerplate(template: string, marker: string): void {
    const current = this.editor.state.doc.toString();
    if (current.includes(marker)) {
      this.editor.focus();
      return;
    }
    const next = current.trim()
      ? `${current.trimEnd()}\n\n${template}`
      : template;
    this.editor.dispatch({
      changes: { from: 0, to: current.length, insert: next },
      selection: { anchor: next.length },
      scrollIntoView: true,
    });
    this.editor.focus();
  }

  /** Releases CodeMirror observers and DOM event handlers. */
  public destroy(): void {
    this.editor.destroy();
  }
}

export const MARKDOWN_IMAGE_CSS_BOILERPLATE_MARKER =
  MARKDOWN_IMAGE_CSS_TEMPLATE_MARKER;
export const TRANSCLUSION_CSS_BOILERPLATE_MARKER =
  TRANSCLUSION_CSS_TEMPLATE_MARKER;
